name: ire4html
description: to be honest I think it's educational 
url: ire4html.tk
permalink: /blog/:year/:month/:day/:title
style: https://ire4ever1190.github.io/foamey/CSS/css.css
nav: navbar.html
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-avatar
collections:
